image: node:8.1.2

clone:
  depth: full
pipelines:
  branches:
    master:
      - step:
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD